In [1]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pickle

def new_pred(fn):
    df= pd.read_csv(fn ,delimiter=" ", skiprows=[0], header=None,)
    df = df.rename(columns={1: 'Gender', 2: 'Age', 3: 'Annual Income (k$)' ,4: 'Spending Score (1-100)'})
    df=df.drop(columns=[0])
    df=df.replace('Male',1)
    df=df.replace('Female',2)
    minobs = min(df.value_counts('Gender').values)
    df = df.groupby('Gender').sample(n=minobs, random_state=1).sample(frac=1, random_state=1)
    display(df)
    clf2, Xmax2 = pickle.load(open('ccd.pkl', 'rb'))
    
    
    f= open("new_Log.txt", "w")
    f.write("Variables"+ " \t"+ "Real Gender"+ " \t" + "Predicted Gender"+ "\n")
    i=0
    c=0
    df=df.to_numpy()
    
    for line in df:
        p=clf2.predict(df[i][1:].reshape(1, -1)/ Xmax2)
        f.write(str(df[i][1:])+ "\t\t" +str(df[i][:1]) + "\t\t" +str(p)+"\n")
        if p==df[i][:1]:
            c+=1
        i+=1
        if i==20:
            break
    f.write("\n\n"+ "Right Guesses"+"\t\t" + str(c) +"/20")
    

    
new_pred("Mall.txt")

     Gender  Age  Annual Income (k$)  Spending Score (1-100)
46        2   50                  40                      55
175       2   30                  88                      86
158       1   34                  78                       1
70        1   70                  49                      55
126       1   43                  71                      35
..      ...  ...                 ...                     ...
94        2   32                  60                      42
186       2   54                 101                      24
55        1   47                  43                      41
124       2   23                  70                      29
33        1   18                  33                      92

[176 rows x 4 columns]