In [1]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

def predictor(fn):
    df= pd.read_csv(fn ,delimiter=" ", skiprows=[0], header=None,)
    df = df.rename(columns={1: 'Gender', 2: 'Age', 3: 'Annual Income (k$)' ,4: 'Spending Score (1-100)'})
    df=df.drop(columns=[0])
    df=df.replace('Male',1)
    df=df.replace('Female',2)

    minobs = min(df.value_counts('Gender').values)
    df = df.groupby('Gender').sample(n=minobs, random_state=1).sample(frac=1, random_state=1)
    data= np.asarray(df)
    display(df)

    X= data[20:, 1:]
    Xmax = X.max(0)
    X = X / Xmax
    Y= data[20:, 0]

    
    #print(X)
    print(X.shape, Y.shape)

    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
    print('training size:', X_train.shape[0], 
           'testing size:', X_test.shape[0],
           'label counts:', np.unique(y_train, return_counts=True)[1])

    clf = MLPClassifier(hidden_layer_sizes=(100,20),
                        max_iter=50).fit(X_train, y_train)

    print('score train:', clf.score(X_train, y_train))
    print('score test: ', clf.score(X_test, y_test))


    with open("Log.txt", "w") as f:
        print('score train:', clf.score(X_train, y_train), file=f)
        print('score test: ', clf.score(X_test, y_test), file=f)
        print('pred prob CLF I: ', clf.predict_proba(X[:1]), file=f)
        print('pred class CLF I:', clf.predict(X[:1]), file =f)
        
    print('pred prob CLF I: ', clf.predict_proba(X[:1]))
    print('pred class CLF I:', clf.predict(X[:1]))
    
    import pickle
    pickle.dump((clf, Xmax), open('ccd.pkl', 'wb'))
    
    clf2, Xmax2 = pickle.load(open('ccd.pkl', 'rb'))
    

    print('pred class CLF II:', clf2.predict(X[:1]))
    #print(df.iloc[20:, 1:])
    print('pred prob CLF I: ', clf2.predict_proba(df.iloc[20:21, 1:]/Xmax2))

predictor("Mall.txt")

     Gender  Age  Annual Income (k$)  Spending Score (1-100)
46        2   50                  40                      55
175       2   30                  88                      86
158       1   34                  78                       1
70        1   70                  49                      55
126       1   43                  71                      35
..      ...  ...                 ...                     ...
94        2   32                  60                      42
186       2   54                 101                      24
55        1   47                  43                      41
124       2   23                  70                      29
33        1   18                  33                      92

[176 rows x 4 columns]

(156, 3) (156,)
training size: 124 testing size: 32 label counts: [63 61]
score train: 0.5887096774193549
score test:  0.34375

/opt/conda/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(

pred prob CLF I:  [[0.47818256 0.52181744]]
pred class CLF I: [2]
pred class CLF II: [2]
pred prob CLF I:  [[0.47818256 0.52181744]]